@startuml
User -> GitHub: README.md
User -> GitHub: http://pointillism.io/your/link.pu
GitHub --> pointillism.io: GET pointillism.io image
GitHub <-- pointillism.io: GET GitHub resource
GitHub <-- pointillism.io: cache image
User <- GitHub: deliver image
@enduml